name: furniture_flutter_app
description: "this app is open source for practice"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.6.7
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.7
  dio: ^5.0.3
  flutter_svg: ^2.0.9
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1
  intl: ^0.18.1
  google_fonts: ^6.1.0
  dartz: ^0.10.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/



